# Generated by Django 2.2.11 on 2020-03-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
