# Generated by Django 2.2.10 on 2020-02-28 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20200226_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='created_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
