# Generated by Django 2.2.10 on 2020-02-29 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_auto_20200229_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverification',
            name='created_date_time',
        ),
    ]
