# Generated by Django 2.2.10 on 2020-02-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_remove_userverification_created_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
