# Generated by Django 2.2.10 on 2020-02-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_userverification_created_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverification',
            name='created_date_time',
        ),
    ]
