# Generated by Django 2.2.10 on 2020-02-29 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_remove_userverification_created_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='created_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
