# Generated by Django 2.2.10 on 2020-02-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_userverification_created_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='created_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
