# Generated by Django 2.2.11 on 2020-03-06 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Product Title', max_length=200)),
                ('price', models.IntegerField(help_text='Enter Product Unit Cost')),
                ('sku', models.CharField(help_text='Enter Product Stock Keeping Unit', max_length=200)),
                ('quantity', models.IntegerField(help_text='Enter Product Quantity')),
                ('discription', models.TextField(help_text='Enter Product Description')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('buffer_quantity', models.IntegerField(help_text='Enter Buffer Stock Quantity')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Subcategory')),
            ],
        ),
    ]
