# Generated by Django 2.2.10 on 2020-02-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_ordered_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_item',
            field=models.TextField(),
        ),
    ]
