# Generated by Django 2.2.10 on 2020-02-28 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200228_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_item',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
