# Generated by Django 2.2.10 on 2020-02-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200228_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('CANCEL', 'Cancel')], default='PLACED', max_length=100),
        ),
    ]
